CREATE TABLE bip_2015_07 (
	bbl BIGINT NOT NULL, 
	address VARCHAR(27) NOT NULL, 
	res_unit INTEGER NOT NULL, 
	tot_unit INTEGER NOT NULL, 
	num_floors INTEGER NOT NULL, 
	census_tract FLOAT NOT NULL, 
	zip_code INTEGER NOT NULL, 
	"BOROCODE" INTEGER NOT NULL, 
	"BLOCK" VARCHAR(5) NOT NULL, 
	"LOT" VARCHAR(4) NOT NULL, 
	"COMMDIST" INTEGER NOT NULL, 
	"LUCATEGORY" VARCHAR(42), 
	year_built INTEGER NOT NULL, 
	yr_1st_alt INTEGER NOT NULL, 
	yr_2nd_alt INTEGER NOT NULL, 
	bldg_class VARCHAR(2) NOT NULL, 
	zoning_gen VARCHAR(17) NOT NULL, 
	zoning VARCHAR(9) NOT NULL, 
	"Violations Current as of " DATE NOT NULL, 
	"Open_Violations" INTEGER NOT NULL, 
	"Open_A_Violations" INTEGER NOT NULL, 
	"Open_B_Violations" INTEGER NOT NULL, 
	"Open_C_Violations" INTEGER NOT NULL, 
	"Open_I_Violations" INTEGER NOT NULL, 
	"PriorYear_Violations" INTEGER NOT NULL, 
	"PriorYear_A_Violations" INTEGER NOT NULL, 
	"PriorYear_B_Violations" INTEGER NOT NULL, 
	"PriorYear_C_Violations" INTEGER NOT NULL, 
	"7A" INTEGER NOT NULL, 
	"AEP" INTEGER NOT NULL, 
	"PPI" INTEGER NOT NULL, 
	"Underlying_Conditions" INTEGER NOT NULL, 
	"NYC 421A Exempt Properties" INTEGER NOT NULL, 
	"PriorYear_311 Comps" INTEGER, 
	"PriorYear_V_to_C_Ratio" FLOAT, 
	dob_violation INTEGER NOT NULL, 
	ecb_violation INTEGER NOT NULL, 
	city_lien FLOAT NOT NULL, 
	"ERPs" FLOAT NOT NULL, 
	"Water" FLOAT, 
	"SoldLiensOpen" FLOAT NOT NULL, 
	"Umbrella" VARCHAR(28), 
	party_name VARCHAR(61), 
	document_type VARCHAR(30), 
	doc_amount FLOAT, 
	recorded_filed VARCHAR(22), 
	"Absolute" FLOAT NOT NULL, 
	"Per Unit" FLOAT NOT NULL, 
	"Current BIP_Score" FLOAT NOT NULL, 
	"Score_2015April" FLOAT, 
	"Score_2015Jan" FLOAT, 
	"Score_2014Oct" FLOAT, 
	"Score_2014Jun" FLOAT, 
	"Score_2014Feb" FLOAT, 
	"Score_2013Nov" FLOAT, 
	"Score_2013Aug" FLOAT, 
	"Score_2013April" FLOAT, 
	"Score_2012Nov" FLOAT, 
	"Score_2012June" FLOAT, 
	"Score_2012Jan" FLOAT, 
	"Score_2010-2" FLOAT, 
	"Score_2010-1" FLOAT, 
	"Score_2009-2" FLOAT, 
	"Score_2009-1" FLOAT, 
	"Score_2008-2" FLOAT, 
	"Occurance" INTEGER NOT NULL, 
	"Average" FLOAT NOT NULL, 
	"CDFAvg" FLOAT NOT NULL, 
	"CorpName" VARCHAR(50), 
	"CorpStreetNum" VARCHAR(12), 
	"CorpStreet" VARCHAR(32), 
	"CorpApt" VARCHAR(6), 
	"CorpCity" VARCHAR(15), 
	"CorpState" VARCHAR(4), 
	"CorpZip" VARCHAR(9), 
	"IndivFirstName" VARCHAR(15), 
	"IndivLastName" VARCHAR(25), 
	"IndivStreetNum" VARCHAR(12), 
	"IndivStreet" VARCHAR(32), 
	"IndivApt" VARCHAR(6), 
	"IndivCity" VARCHAR(15), 
	"IndivSt" VARCHAR(4), 
	"IndivZip" VARCHAR(9), 
	"HeadOffTitle" VARCHAR(15), 
	"HeadOffFirstName" VARCHAR(15), 
	"HeadOffLastName" VARCHAR(25), 
	"HeadOffStreetNum" VARCHAR(12), 
	"HeadOffStreet" VARCHAR(32), 
	"HeadOffApt" VARCHAR(7), 
	"HeadOffCity" VARCHAR(15), 
	"HeadOffSt" VARCHAR(4), 
	"HeadOffZip" VARCHAR(9), 
	"MngmtCorp" VARCHAR(50), 
	"MngmtFirstName" VARCHAR(15), 
	"MngmtLastName" VARCHAR(24), 
	"MngmtStreetNum" VARCHAR(12), 
	"MngmtStreet" VARCHAR(32), 
	"MngmtApt" VARCHAR(6), 
	"MngmtCity" VARCHAR(15), 
	"MngmtSt" VARCHAR(4), 
	"MngmtZip" VARCHAR(9)
);
